[tool.pytest.ini_options]
pythonpath = "src/"
addopts = "-vv -p no:cacheprovider --disable-warnings"
testpaths = ["tests/"]
python_files = ["test_*.py"]
asyncio_mode= "auto"

[tool.aerich]
tortoise_orm = "configs.db.TORTOISE_ORM"
location = "./src/migrations"
src_folder = "./src"
